### ISSUE TITLE
Python error, Kodi for Windows: cannot import name 'client' from 'resources.lib.modules'

### ISSUE THREAD

**Issue by EvilCaptKirk** [team-crew/team-crew.github.io#105]
Kodi 19.4 on Windows 10, latest The Crew from this repo. The issue appeared sometime in the past week. Have tried the following troubleshooting steps:

1. uninstall/reinstall The Crew addon;
2. resetting Kodi (deleting Kodi folder in %appdata%), then reinstalling The Crew et al;
3. full fresh install of Kodi and The Crew. 

1 has no effect. 2 or 3 fix The Crew for exactly one use (search item, play found result), then the error repeats, and reset must be repeated to restore functionality. 

Here's the error. I don't know jack all about Python or Kodi internals, so any tips to resolve are appreciated:

2022-10-21 08:25:26.610 T:36628    INFO <general>: Python interpreter stopped
2022-10-21 08:25:26.616 T:32972   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.thecrew/?action=searchNavigator
2022-10-21 08:25:26.617 T:36688   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.thecrew/?action=searchNavigator) failed
2022-10-21 08:25:28.115 T:25760    INFO <general>: initializing python engine.
2022-10-21 08:25:28.500 T:25760   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'client' from 'resources.lib.modules' (C:\Path\To\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\modules\__init__.py)
                                                   Traceback (most recent call last):
                                                     File "C:\Path\To\AppData\Roaming\Kodi\addons\plugin.video.thecrew\thecrew.py", line 493, in <module>
                                                       from resources.lib.indexers import navigator
                                                     File "C:\Path\To\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\indexers\navigator.py", line 30, in <module>
                                                       from resources.lib.modules import trakt
                                                     File "C:\Path\To\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\modules\trakt.py", line 37, in <module>
                                                       from resources.lib.modules import client
                                                   ImportError: cannot import name 'client' from 'resources.lib.modules' (C:\Path\To\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\modules\__init__.py)
                                                   -->End of Python script error report<--

**Comment by EvilCaptKirk** [comment]
Closing this - looks like Bitdefender got excited and put some files in quarantine, which naturally borked The Crew.
