### ISSUE TITLE
The Crew won’t open - Memory leak warning in log

### ISSUE THREAD

**Issue by manrata** [team-crew/team-crew.github.io#125]
Suddenly just after watching movie, The Crew add-on won’t open anymore, just tells me to check log for errors. 

Log error change a little in line etc. But they are all more or less like below.

Have tried uninstalling and reinstalling add-on, including deleting cached data using Open Wizard.
Also tried deleting all The Crew folders before reinstalling so it wouldn’t have anything cached, but to no avail.

Can see others with similar errors years ago, but no solution.

Kodi version is 19.4.0

Log error:

EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'OSError'>
                                                   Error Contents: [Errno 22] Invalid argument: 'C:\\Users\\trust\\AppData\\Roaming\\Kodi\\addons\\script.module.thecrew\\lib\\resources\\lib\\modules\\client.py'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\trust\AppData\Roaming\Kodi\addons\plugin.video.thecrew\thecrew.py", line 82, in <module>
                                                       from resources.lib.indexers import navigator
                                                     File "C:\Users\trust\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\indexers\navigator.py", line 30, in <module>
                                                       from resources.lib.modules import trakt
                                                     File "C:\Users\trust\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\modules\trakt.py", line 38, in <module>
                                                       from resources.lib.modules import client
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 715, in exec_module
                                                     File "<frozen importlib._bootstrap_external>", line 851, in get_code
                                                     File "<frozen importlib._bootstrap_external>", line 908, in get_data
                                                   OSError: [Errno 22] Invalid argument: 'C:\\Users\\trust\\AppData\\Roaming\\Kodi\\addons\\script.module.thecrew\\lib\\resources\\lib\\modules\\client.py'
                                                   -->End of Python script error report<--

**Comment by fade2gray** [comment]
Your Kodi version isn't just "19" - check to see if it hasn't updated to 19.5 which The Crew isn't currently compatible with.

**Comment by manrata** [comment]
It’s 19.4.0, updated post.

**Comment by TrillaG** [comment]
Mine's not working either. Looks like it finally broke completely. Not much hope for a fix imho.

**Comment by fade2gray** [comment]
Just a thought, there was a recent issue with the Trakt database - maybe reauthorising Trakt may fix it? Otherwise you cauld try contacting the devs via Telegram - see #108.

**Comment by fade2gray** [comment]
Seems like your antivirus may have silently quarantined some files - see #105.

**Comment by TrillaG** [comment]
Nah that has nothing to do with it I never authorized trakt on the crew in the first place. And I don't have an antivirus either. And I did contact dev months ago when issue started -- they said they'd look and nothing ever got done. And now the link doesn't work as others have said before. No hope, as I said before.

**Comment by manrata** [comment]
I don't use Trakt, and only use Windows Defender, I can check, but I doubt it can quarantine files.

**Comment by fade2gray** [comment]
If you try reinstalling, temporarily disable `Real-time protection` in Windows Security.

**Comment by Arvo1377** [comment]
having the same issue here for a couple days now, trakt wasnt authorized for me either and i never got anything from my AV plus i have kodi allowed for it. i think their update isnt playing nice with something

**Comment by fade2gray** [comment]
I think you'll find it has to do with #117 and Windows recent update to virus definitions.

To prove a point, I've just reinstalled Kodi 19.4 with the current TC repo and add-on - Just select Actions > Allow.

![PythonMalware](https://user-images.githubusercontent.com/1332009/215270317-c7e715ea-2491-476e-be1d-2c270c60da55.png)

**Comment by manrata** [comment]
@fade2gray you were absolutely right, Windows Defender had qurantined exactly those two files.

So solved!

Thank you so very much, I like Shadow, but the crew is superior in organisation. 

A deep bow to you, and I’ll close the thread.
