### ISSUE TITLE
The Crew ERROR

### ISSUE THREAD

**Issue by CelinaFromCHMBX** [team-crew/team-crew.github.io#132]
Hello,

I've just reinstalled my complete KODI interface on Win10 and installed the repo. Only. When i want to start The Crew addon i get the message The Crew ERROR. See log for more information. See below what i've found in my logfile. 

The addon won't start in any way... Can you help?

2023-03-23 18:22:12.732 T:5096    error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2023-03-23 18:22:13.288 T:2664    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'client' from 'resources.lib.modules' (C:\Users\Mediacentrum\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\modules\__init__.py)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Mediacentrum\AppData\Roaming\Kodi\addons\plugin.video.thecrew\thecrew.py", line 82, in <module>
                                                       from resources.lib.indexers import navigator
                                                     File "C:\Users\Mediacentrum\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\indexers\navigator.py", line 30, in <module>
                                                       from resources.lib.modules import trakt
                                                     File "C:\Users\Mediacentrum\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\modules\trakt.py", line 38, in <module>
                                                       from resources.lib.modules import client
                                                   ImportError: cannot import name 'client' from 'resources.lib.modules' (C:\Users\Mediacentrum\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\modules\__init__.py)
                                                   -->End of Python script error report<--
                                                   
2023-03-23 18:22:13.413 T:2740    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.thecrew/
2023-03-23 18:22:13.423 T:5096    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.thecrew/) failed
2023-03-23 18:22:20.876 T:2948    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'client' from 'resources.lib.modules' (C:\Users\Mediacentrum\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\modules\__init__.py)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Mediacentrum\AppData\Roaming\Kodi\addons\plugin.video.thecrew\thecrew.py", line 82, in <module>
                                                       from resources.lib.indexers import navigator
                                                     File "C:\Users\Mediacentrum\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\indexers\navigator.py", line 30, in <module>
                                                       from resources.lib.modules import trakt
                                                     File "C:\Users\Mediacentrum\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\modules\trakt.py", line 38, in <module>
                                                       from resources.lib.modules import client
                                                   ImportError: cannot import name 'client' from 'resources.lib.modules' (C:\Users\Mediacentrum\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\modules\__init__.py)
                                                   -->End of Python script error report<--
                                                   
2023-03-23 18:22:21.016 T:11604   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.thecrew/
2023-03-23 18:22:21.032 T:5096    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.thecrew/) failed

**Comment by fade2gray** [comment]
This is a [known issue](https://github.com/team-crew/team-crew.github.io/issues/125#issuecomment-1407405060) with recent Windows antivirus definition updates detecting certain TheCrew files as a trojan - it's a false-positive.

Check your `Windows Security > Virus & threat protection > Protection history` for any relative files that have been quarantined, and permit them by selecting `Actions > Allow`.

![quarantine](https://user-images.githubusercontent.com/1332009/227299892-c6a18a01-74d9-497c-bd10-e1f5e336c92c.png)

**Comment by CelinaFromCHMBX** [comment]
Thank you, this solved all!
