### ISSUE TITLE
Error Report on scraping for movie.

### ISSUE THREAD

**Issue by TheFantasticLoki** [team-crew/team-crew.github.io#51]
No idea how you want this formatted @thecrewwh But I have had a couple movies that cause this including Fast & Furious 6 where it scrapes then on completion errors out. Here is the error from the log file.

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'simplejson.errors.JSONDecodeError'>
                                                   Error Contents: Unterminated string starting at: line 1 column 315 (char 314)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\plugin.video.thecrew\thecrew.py", line 725, in <module>
                                                       sources.sources().addItem(title)
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.thecrew\lib\resources\lib\modules\sources.py", line 127, in addItem
                                                       meta = json.loads(meta)
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\__init__.py", line 525, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\decoder.py", line 370, in decode
                                                       obj, end = self.raw_decode(s)
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\decoder.py", line 400, in raw_decode
                                                       return self.scan_once(s, idx=_w(s, idx).end())
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\scanner.py", line 79, in scan_once
                                                       return _scan_once(string, idx)
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\scanner.py", line 44, in _scan_once
                                                       return parse_object((string, idx + 1), encoding, strict,
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\decoder.py", line 194, in JSONObject
                                                       value, end = scan_once(s, end)
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\scanner.py", line 42, in _scan_once
                                                       return parse_string(string, idx + 1, encoding, strict)
                                                     File "C:\Users\astey\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\decoder.py", line 68, in py_scanstring
                                                       raise JSONDecodeError(
                                                   simplejson.errors.JSONDecodeError: Unterminated string starting at: line 1 column 315 (char 314)
                                                   -->End of Python script error report<--

**Comment by TheFantasticLoki** [comment]
Seems to happen on any movie/tv show whatever that has an & symbol in the title.

**Comment by TheFantasticLoki** [comment]
Also not limited to The Crew also happens on The Oath but I can't find their github page to make an issue.

**Comment by jmh2002** [comment]
> Also not limited to The Crew also happens on The Oath but I can't find their github page to make an issue.

The Oath is here: https://github.com/host505/plugin.video.theoath/issues

**Comment by thecrewwh** [comment]
Cant replicate your issue

**Comment by TheFantasticLoki** [comment]
Maybe if I just post my Kodi.log you could get more info from that since there are a lot of errors and weird warnings but I just started using kodi again so I don't know how to fix them all. Just a standard Diggzrepo Chef Wizard install with Netflix addon added but still had issues before that.
[kodi.log](https://github.com/team-crew/team-crew.github.io/files/6592040/kodi.log)

**Comment by thecrewwh** [comment]
You have a lot of stuff on that system and Not familiar with the wizard or builds I would say try from scratch first to see if that fixes your issue then you know it is your build since I cant reproduce the issue
